export enum ActionTypes {
  EXAMPLE = 'EXAMPLE',
  AIRLOCK_OPEN = 'AIRLOCK_OPEN',

  LOADING_STATE_RESET   = 'LOADING_STATE_RESET',
  INITIAL_SET = 'INITIAL_SET',
  LOADING_SET = 'LOADING_SET',
  SUCCESS_SET = 'SUCCESS_SET',
  ERROR_SET   = 'ERROR_SET',
}
